# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'



target 'CNCMobStreamLibDemoFU' do
  
  
   pod 'SVProgressHUD'
   pod 'FLAnimatedImage'
   pod 'Masonry'
   pod 'AFNetworking'
   pod 'SDWebImage'
   pod 'MJExtension'
   pod 'SVProgressHUD'
   pod 'Nama', '~> 7.2.0'

end
