# Uncomment the next line to define a global platform for your project
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
 platform :ios, '9.0'



target 'CNCMobStreamLibDemoFU' do
  
  
   pod 'SVProgressHUD'
   pod 'FLAnimatedImage'
   pod 'Masonry'
   pod 'AFNetworking'
   pod 'SDWebImage'
   pod 'MJExtension'
   pod 'SVProgressHUD'
   pod 'FURenderKit', '~> 8.7.0'

end
